# Generated by Django 5.2.2 on 2025-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GreaterPotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase', models.PositiveIntegerField(blank=True, help_text='Price in gold coins (gc)', null=True)),
                ('sale', models.PositiveIntegerField(blank=True, help_text='Price in gold coins (gc)', null=True)),
                ('die_roll', models.PositiveIntegerField(blank=True, help_text='Dice roll required to obtain this item', null=True)),
                ('ingredient_cost', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LesserPotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase', models.PositiveIntegerField(blank=True, help_text='Price in gold coins (gc)', null=True)),
                ('sale', models.PositiveIntegerField(blank=True, help_text='Price in gold coins (gc)', null=True)),
                ('die_roll', models.PositiveIntegerField(blank=True, help_text='Dice roll required to obtain this item', null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase', models.PositiveIntegerField(blank=True, help_text='Price in gold coins (gc)', null=True)),
                ('sale', models.PositiveIntegerField(blank=True, help_text='Price in gold coins (gc)', null=True)),
                ('die_roll', models.PositiveIntegerField(blank=True, help_text='Dice roll required to obtain this item', null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MagicWeaponOrArmour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('purchase', models.PositiveIntegerField(blank=True, help_text='Price in gold coins (gc)', null=True)),
                ('sale', models.PositiveIntegerField(blank=True, help_text='Price in gold coins (gc)', null=True)),
                ('die_roll', models.PositiveIntegerField(blank=True, help_text='Dice roll required to obtain this item', null=True)),
                ('effects', models.CharField(blank=True, help_text='Effect of the magic weapon or armour', max_length=255, null=True)),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RandomSpell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_roll', models.PositiveIntegerField(blank=True, help_text='Dice roll required to obtain this spell', null=True)),
                ('second_die_1_to_5', models.CharField(blank=True, help_text='If second die roll result is between 1 and 5, this happens', max_length=255, null=True)),
                ('second_die_6_to_10', models.CharField(blank=True, help_text='If second die roll result is between 6 and 10, this happens', max_length=255, null=True)),
                ('second_die_11_to_15', models.CharField(blank=True, help_text='If second die roll result is between 11 and 15, this happens', max_length=255, null=True)),
                ('second_die_16_to_20', models.CharField(blank=True, help_text='If second die roll result is between 16 and 20, this happens', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('die_roll', models.PositiveIntegerField(blank=True, help_text='Dice roll required to obtain this treasure', null=True)),
                ('gold', models.PositiveIntegerField(blank=True, help_text='Amount of gold coins (gc) in the treasure', null=True)),
                ('multiply_gold_by_d20', models.BooleanField(default=False, help_text='Multiply the gold amount by a d20 roll')),
                ('result', models.CharField(blank=True, help_text='Description of the treasure result, in addition to the gold amount', max_length=255, null=True)),
            ],
        ),
    ]
