# GitHub Actions workflow to build and push Docker image
name: Build and Push to GCP

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GCP_REGION: europe-west2
  GCP_PROJECT_ID: frostgrave-reborn

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3

  build-and-push:
    runs-on: ubuntu-latest
    needs: ruff
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Read GCP AR and CR Service from local json file
        id: read-gcp-ar
        run: echo "registry_path=$(jq -r '.registry_location.value' .tf/output.json)" >> $GITHUB_OUTPUT && \
          echo "service_name=$(jq -r '.service_name.value' .tf/output.json)" >> $GITHUB_OUTPUT
      
      - name: Auth for gcloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: "${{ env.GCP_PROJECT_ID }}"
      
      - name: Configure Docker to use gcloud as a credential helper
        run: |
          gcloud auth configure-docker "${{ env.GCP_REGION }}-docker.pkg.dev" --quiet
      
      - name: Build Docker image
        run: |
          docker build -t "${{ steps.read-gcp-ar.outputs.registry_path }}/image:latest" .
      
      - name: Push Docker image
        run: |
          docker push "${{ steps.read-gcp-ar.outputs.registry_path }}/image:latest"

      - name: Short sleep to ensure image is available
        run: sleep 5

      - name: New revision of the Cloud Run service
        run: |
          gcloud run ${{ steps.read-gcp-ar.outputs.service_name }} \
            --quiet